AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for EventBridge Ruleliwords-hourly-maintenance
Resources:
  Rule2a345984:
    Type: AWS::Events::Rule
    Properties:
      Name: liwords-hourly-maintenance
      ScheduleExpression: cron(4 * * * ? *)
      State: ENABLED
      Description: Hourly maintenance for liwords. Only hourly tasks should go here.
      EventBusName: default
      Targets:
        - Id: Id0a83945c-2c6b-433f-b849-e3ac7e322174
          Arn:
            Fn::Sub: >-
              arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/woogles-prod
          RoleArn:
            Fn::Sub: arn:${AWS::Partition}:iam::${AWS::AccountId}:role/ecsEventsRole
          Input: Fn::Sub: |-
            {
                "taskRoleArn": "arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole",
                "containerOverrides": [
                    {
                        "name": "maintenance",
                        "command": [
                            "/opt/maintenance",
                            "blogrss-updater,sub-badge-updater"
                        ]
                    }
                ]
            }
          EcsParameters:
            TaskDefinitionArn: Fn::Sub: >-
              arn:aws:ecs:us-east-2:${AWS::AccountId}:task-definition/liwords-maintenance
            TaskCount: 1
            LaunchType: EC2
            EnableECSManagedTags: false
            EnableExecuteCommand: false
Parameters: {}
