version: 2.1
orbs:
  discord: antonioned/discord@0.1.0
  codecomet-orb: codecomet/codecomet-orb@0.3.1
jobs:
  build_api_srv:
    environment:
      MACONDO_DATA_PATH: /opt/liwords/data
      # Needed for running local tests that use the database:
      TEST_DB_HOST: localhost
      TEST_DB_NAME: liwords_test
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: pass
      DB_SSL_MODE: disable
      DB_MIGRATIONS_PATH: file:///opt/liwords/db/migrations

      REDIS_URL: redis://localhost:6379
    docker:
      - image: golang
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: liwords_test
          POSTGRES_PASSWORD: pass
      - image: circleci/redis

    working_directory: /opt/liwords
    steps:
      - checkout
      - run:
          name: Clone macondo
          command: git clone --depth 1 git@github.com:domino14/macondo /opt/macondo
      - run: cd cmd/liwords-api && go build
      - codecomet-orb/install
      - codecomet-orb/ingest:
          # Tests must not be run in parallel; postgres issues happen otherwise.
          test_command: go test -race -p 1 ./...
          test_suite_name: liwords-backend-tests
      # - run: for s in $(go list ./...); do if ! ./codecomet -s liwords-backend-tests -- go test -failfast -race -v -p 1 $s; then break; fi; done
      # Make sure puzzle generator builds too, since we're deploying that docker image.
      - run: cd cmd/puzzlegen && go build
      - run: cd cmd/maintenance && go build
      - discord/status: &discord-webhook-setting
          webhook: "${DISCORD_WEBHOOK}"
          success_message: ":tada: A $CIRCLE_JOB job has succeeded! (Branch: $CIRCLE_BRANCH)"
          failure_message: ":red_circle: A $CIRCLE_JOB job has failed! (Branch: $CIRCLE_BRANCH)"

  deploy_api_docker:
    machine: true
    steps:
      - checkout
      - run: echo $GHCR_TOKEN | docker login ghcr.io -u domino14 --password-stdin
      - run: >
          docker build --build-arg BUILD_HASH=${CIRCLE_SHA1}
          --build-arg BUILD_DATE=$(date -Iseconds -u)
          -t ghcr.io/woogles-io/liwords-api:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM} .
      - run: docker push ghcr.io/woogles-io/liwords-api:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
      - run: >
          docker build --build-arg BUILD_HASH=${CIRCLE_SHA1}
          --build-arg BUILD_DATE=$(date -Iseconds -u)
          -t ghcr.io/woogles-io/liwords-puzzlegen:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
          -f Dockerfile-puzzlegen .
      - run: docker push ghcr.io/woogles-io/liwords-puzzlegen:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
      - run: >
          docker build --build-arg BUILD_HASH=${CIRCLE_SHA1}
          --build-arg BUILD_DATE=$(date -Iseconds -u)
          -t ghcr.io/woogles-io/liwords-maintenance:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
          -f Dockerfile-maintenance .
      - run: docker push ghcr.io/woogles-io/liwords-maintenance:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
      - discord/status: *discord-webhook-setting

  build_fe:
    working_directory: /opt/liwords
    docker:
      - image: node:lts
    steps:
      - checkout
      - run: cd liwords-ui && npm ci
      - run: cd liwords-ui && npm run test -- --reporter=junit --outputFile=junit-test.xml
      - codecomet-orb/install
      - codecomet-orb/ingest_junit:
          junit_file: liwords-ui/junit-test.xml
          test_suite_name: liwords-frontend-tests
      - run: cd liwords-ui && npm run build
      - persist_to_workspace:
          root: liwords-ui
          paths:
            - dist
      - discord/status: *discord-webhook-setting

  deploy_fe:
    docker:
      - image: amazon/aws-cli
    steps:
      - run: yum install -y tar gzip md5sum which
      - attach_workspace:
          at: /tmp/liwords-ui
      - run: >
          UI_HASH=$(find /tmp/liwords-ui/dist -type f -exec md5sum {} \; | sort -k 2 | md5sum | head -c 32) &&
          echo $UI_HASH &&
          sed -i "s:unknown:${UI_HASH}:" /tmp/liwords-ui/dist/config.js &&
          echo "export UI_HASH=$UI_HASH" >> $BASH_ENV

      # cache everything except index.html, config files, and wasm file
      - run: >
          cd /tmp/liwords-ui/dist &&
          aws s3 sync --cache-control 'max-age=3024000'
          --exclude index.html --exclude config.js --exclude '*.wasm'
          --metadata FEHash=${UI_HASH}
          . s3://woogles.io
      # no-cache everything except the wasm file
      - run: >
          cd /tmp/liwords-ui/dist &&
          aws s3 sync --cache-control 'no-cache' --exclude '*.wasm'
          --metadata FEHash=${UI_HASH}
          . s3://woogles.io
      # cache the wasm file separately. We can't put it in the first sync call above
      # because we require the content-type to be set properly.
      - run: >
          cd /tmp/liwords-ui/dist &&
          aws s3 sync --cache-control 'max-age=3024000' --exclude '*' --include '*.wasm'
          --metadata FEHash=${UI_HASH}
          --content-type 'application/wasm' . s3://woogles.io
      - run: >
          curl -X POST -H "Content-Type: application/json"
          -H "X-Api-Key: ${ADMIN_WOOGLES_API_KEY}"
          https://woogles.io/twirp/config_service.ConfigService/SetFEHash
          -d "{\"hash\": \"${UI_HASH}\"}"

      - discord/status: *discord-webhook-setting

workflows:
  version: 2
  build_app:
    jobs:
      - build_api_srv
      - build_fe
      - deploy_api_docker:
          context:
            - woogles-prod-deploy
          requires:
            - build_api_srv
          filters:
            branches:
              only:
                - master

      - deploy_fe:
          requires:
            - build_fe
          filters:
            branches:
              only:
                - master
